document.writeln("<link type=\'text/css\' rel=\'stylesheet\' href=\'https://www.xuewangzhan.net/wp-content/themes/xwz/images/js/kefu/kf20519.css\'>");
document.writeln("<div class=\'bsk_rightBar\' id=\'goTop\' style=\'display: block;\'>");
document.writeln("	<div class=\'kftit\'>在线<br>客服</div>");
document.writeln("      <div class=\'link_a\'>");
document.writeln("        <img src=\'https://www.xuewangzhan.net/wp-content/themes/xwz/images/js/kefu/ritBarIcon2.png\' class=\'img0\'>");
document.writeln("		<img src=\'https://www.xuewangzhan.net/wp-content/themes/xwz/images/js/kefu/ritBarIcon21.png\' class=\'img1\'>");
document.writeln("        <div class=\'chis\'>");
document.writeln("            <i class=\'ars\'></i>");
document.writeln("            <div class=\'cIns\'>");
document.writeln("                <div class=\'csIn\'>");
document.writeln("                    <div class=\'colv\'>");
document.writeln("                        <span class=\'tt\'>QQ在线咨询</span>");
document.writeln("                         <ul class=\'kful\'>");
document.writeln("							<li class=\'skfli01\'>");
document.writeln("									 <a title=\'报名客服李欣蓉\' class=\'btnjs01\'><span style=\'color:#990033\'>客服李欣蓉</span></a>");
document.writeln("								  </li>");
document.writeln("							<li class=\'skfli02\'>");
document.writeln("									<a title=\'报名客服孙 丽\' class=\'btnjs02\'><span style=\'color:#990033\'>客服孙 丽</span></a>");
document.writeln("								  </li>");
document.writeln("							<li class=\'skfli03\'>");
document.writeln("								   <a title=\'报名客服刘淼淼\' class=\'btnjs03\'><span style=\'color:#990033\'>客服刘淼淼</span></a>");
document.writeln("								  </li>");
document.writeln("							<li class=\'skfli04\'>");
document.writeln("									<a title=\'技术讲师张启亚\' class=\'btnjs04\'><span style=\'color:#000066\'>讲师张启亚</span></a>");
document.writeln("								  </li>");
document.writeln("							<li class=\'skfli05\'>");
document.writeln("									<a title=\'技术讲师方重华\' class=\'btnjs05\'><span style=\'color:#000066\'>讲师方重华</span></a>");
document.writeln("								  </li>");
document.writeln("							<li class=\'skfli06\'>");
document.writeln("									<a title=\'技术讲师唐超\' class=\'btnjs06\'><span style=\'color:#000066\'>讲师唐  超</span></a>");
document.writeln("								  </li>");
document.writeln("							<li class=\'skfli07\'>");
document.writeln("									 <a title=\'技术讲师赵鹏\' class=\'btnjs07\'><span style=\'color:#000066\'>讲师赵 鹏</span></a>");
document.writeln("								  </li>");
document.writeln("								  </ul>");
document.writeln("						</div>    ");
document.writeln("                    ");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("	 <a class=\'link_a\' title=\'微信咨询\'>");
document.writeln("        <img src=\'https://www.xuewangzhan.net/wp-content/themes/xwz/images/js/kefu/ritBarIcon5.png\' rel=\'nofollow\' class=\'img0\' alt=\'手机二维码\'>");
document.writeln("		<img src=\'https://www.xuewangzhan.net/wp-content/themes/xwz/images/js/kefu/ritBarIcon51.png\' class=\'img1\' rel=\'nofollow\' alt=\'手机二维码\'>");
document.writeln("        <div class=\'wxgzh\' style=\'background-image:url(https://www.xuewangzhan.net/wp-content/themes/xwz/images/js/kefu/gzhEwm.png)\'></div>");
document.writeln("    </a>");
document.writeln("   ");
document.writeln("    <a class=\'link_a last\' id=\'goTopBtn\' title=\'返回顶部\'><img src=\'https://www.xuewangzhan.net/wp-content/themes/xwz/images/js/kefu/ritBarIcon4.png\' rel=\'nofollow\' class=\'img0\' alt=\'返回顶部\'>");
document.writeln("		<img src=\'https://www.xuewangzhan.net/wp-content/themes/xwz/images/js/kefu/ritBarIcon41.png\' class=\'img1\' alt=\'返回顶部\'>");
document.writeln("    </a>");
document.writeln("</div>");
document.writeln("  <script src=\'/wp-content/themes/xwz/images/jquery-3.1.0.min.js\' type=\'text/javascript\'></script>  ");
document.writeln("<script>");
document.writeln("");
document.writeln("let back=document.getElementById(\'goTopBtn\');");
document.writeln("let duration = 500;");
document.writeln("back.onclick = function () {");
document.writeln("    let l = document.documentElement.scrollTop;");
document.writeln("    console.log(l);");
document.writeln("    let s = l / 600 * 25;  ");
document.writeln("    let st = setInterval(function () {");
document.writeln("        l -= s;");
document.writeln("        if (l <= 0) {");
document.writeln("            l = 0; //当l<=0时，设置l=0");
document.writeln("            clearInterval(st);");
document.writeln("        }");
document.writeln("        document.documentElement.scrollTop = l;");
document.writeln("    }, 25)");
document.writeln("}");
document.writeln("</script>");
document.writeln("<div class=\'dialog dialog01\'>");
document.writeln("        <h3>温馨提示</h3>");
document.writeln("        <p>为防止临时会话收不到QQ信息，请加QQ好友咨询<br/>");
document.writeln("        <span>论坛客服李欣蓉QQ：<em>2289556365</em> </span><br/><br/>");
document.writeln("		或者使用<span>微信</span>扫码咨询<br/>");
document.writeln("		<img src=\'/wp-content/themes/xwz/images/js/kefu/eewm.jpg\' width=\'160px\' />");
document.writeln("              ");
document.writeln("        </p>");
document.writeln("        <a class=\'gbi\'>x</a>        ");
document.writeln("        </div>");
document.writeln("        ");
document.writeln("<div class=\'dialog dialog02\'>");
document.writeln("        <h3>温馨提示</h3>");
document.writeln("        <p>为防止临时会话收不到QQ信息，请加QQ好友咨询<br/>");
document.writeln("        <span>论坛客服孙丽QQ：<em>2399118408</em> </span><br/><br/>");
document.writeln("		或者使用<span>微信</span>扫码咨询<br/>");
document.writeln("		<img src=\'/wp-content/themes/xwz/images/js/kefu/eewm.jpg\' width=\'160px\' />");
document.writeln("              ");
document.writeln("        </p>");
document.writeln("        <a class=\'gbi\'>x</a>        ");
document.writeln("        </div>");
document.writeln("        ");
document.writeln("<div class=\'dialog dialog03\'>");
document.writeln("        <h3>温馨提示</h3>");
document.writeln("        <p>为防止临时会话收不到QQ信息，请加QQ好友咨询<br/>");
document.writeln("        <span>论坛客服刘淼淼QQ：<em>1135082670</em> </span><br/><br/>");
document.writeln("		或者使用<span>微信</span>扫码咨询<br/>");
document.writeln("		<img src=\'/wp-content/themes/xwz/images/js/kefu/eewm.jpg\' width=\'160px\' />");
document.writeln("              ");
document.writeln("        </p>");
document.writeln("        <a class=\'gbi\'>x</a>        ");
document.writeln("        </div>");
document.writeln("        ");
document.writeln("<div class=\'dialog dialog04\'>");
document.writeln("        <h3>温馨提示</h3>");
document.writeln("        <p>为防止临时会话收不到QQ信息，请加QQ好友咨询<br/>");
document.writeln("        <span>论坛讲师张启亚QQ：<em>2357852508</em> </span><br/><br/>");
document.writeln("		或者使用<span>微信</span>扫码咨询<br/>");
document.writeln("		<img src=\'/wp-content/themes/xwz/images/js/kefu/eewm.jpg\' width=\'160px\' />");
document.writeln("              ");
document.writeln("        </p>");
document.writeln("        <a class=\'gbi\'>x</a>        ");
document.writeln("        </div>");
document.writeln("        ");
document.writeln("<div class=\'dialog dialog05\'>");
document.writeln("        <h3>温馨提示</h3>");
document.writeln("        <p>为防止临时会话收不到QQ信息，请加QQ好友咨询<br/>");
document.writeln("        <span>论坛讲师方重华QQ：<em>1730401718</em> </span><br/><br/>");
document.writeln("		或者使用<span>微信</span>扫码咨询<br/>");
document.writeln("		<img src=\'/wp-content/themes/xwz/images/js/kefu/eewm.jpg\' width=\'160px\' />");
document.writeln("              ");
document.writeln("        </p>");
document.writeln("        <a class=\'gbi\'>x</a>        ");
document.writeln("        </div>");
document.writeln("        ");
document.writeln("<div class=\'dialog dialog06\'>");
document.writeln("        <h3>温馨提示</h3>");
document.writeln("        <p>为防止临时会话收不到QQ信息，请加QQ好友咨询<br/>");
document.writeln("        <span>论坛讲师唐超QQ：<em>909722045</em> </span><br/><br/>");
document.writeln("		或者使用<span>微信</span>扫码咨询<br/>");
document.writeln("		<img src=\'/wp-content/themes/xwz/images/js/kefu/eewm.jpg\' width=\'160px\' />");
document.writeln("              ");
document.writeln("        </p>");
document.writeln("        <a class=\'gbi\'>x</a>        ");
document.writeln("        </div>");
document.writeln("        ");
document.writeln("<div class=\'dialog dialog07\'>");
document.writeln("        <h3>温馨提示</h3>");
document.writeln("        <p>为防止临时会话收不到QQ信息，请加QQ好友咨询<br/>");
document.writeln("        <span>论坛讲师赵鹏QQ：<em>614862774 </span><br/><br/>");
document.writeln("		或者使用<span>微信</span>扫码咨询<br/>");
document.writeln("		<img src=\'/wp-content/themes/xwz/images/js/kefu/eewm.jpg\' width=\'160px\' />");
document.writeln("              ");
document.writeln("        </p>");
document.writeln("        <a class=\'gbi\'>x</a>        ");
document.writeln("        </div>");
document.writeln("        ");
document.writeln("<div class=\'dialog dialog08\'>");
document.writeln("        <h3>微信咨询</h3>");
document.writeln("        <p>可使用微信扫下方二维码加好友咨询。<br/><br/>");
document.writeln("        <img src=\'/wp-content/themes/xwz/images/js/kefu/eewm.jpg\' width=\'160px\' />");
document.writeln("              ");
document.writeln("        </p>");
document.writeln("        <a class=\'gbi\'>x</a>        ");
document.writeln("        </div>");
document.writeln("        ");
document.writeln("  <script src=\'/wp-content/themes/xwz/images/js/jquery-3.3.1.min.js\' type=\'text/javascript\'></script>  ");
document.writeln("    <script language=\'javascript\'>  ");
document.writeln("        $(document).ready(function () {  ");
document.writeln("            var menuYloc = $(\'#kfoutbox\').offset().top;  ");
document.writeln("            $(window).scroll(function () {  ");
document.writeln("                var offsetTop = menuYloc + $(window).scrollTop() + \'px\';  ");
document.writeln("                $(\'#kfoutbox\').animate({ top: offsetTop }, { duration: 600, queue: false });  ");
document.writeln("            }); ");
document.writeln("		$(\'#kfboxclose\').click(function(){");
document.writeln("			$(\'#kfoutbox\').hide();");
document.writeln("		  });");
document.writeln("		  ");
document.writeln("");
document.writeln("		$(\'#kfoutbox\').mouseover(function(){");
document.writeln("			$(\'.kfoutbox\').css({\'width\':\'151px\',\'transition\':\'width 0.8s\'});");
document.writeln("		  });");
document.writeln("		  $(\'#kfoutbox\').mouseout(function(){");
document.writeln("			$(\'.kfoutbox\').css(\'width\',\'40px\');");
document.writeln("		  });");
document.writeln("");
document.writeln("        });   ");
document.writeln("    </script>  ");
document.writeln("    ");
document.writeln("<script>");
document.writeln("$(\'.btnjs01\').click(function(){");
document.writeln("$(\'.dialog01\').fadeIn()");
document.writeln("})");
document.writeln("$(\'.btnjs02\').click(function(){");
document.writeln("$(\'.dialog02\').fadeIn()");
document.writeln("})");
document.writeln("$(\'.btnjs03\').click(function(){");
document.writeln("$(\'.dialog03\').fadeIn()");
document.writeln("})");
document.writeln("$(\'.btnjs04\').click(function(){");
document.writeln("$(\'.dialog04\').fadeIn()");
document.writeln("})");
document.writeln("$(\'.btnjs05\').click(function(){");
document.writeln("$(\'.dialog05\').fadeIn()");
document.writeln("})");
document.writeln("$(\'.btnjs06\').click(function(){");
document.writeln("$(\'.dialog06\').fadeIn()");
document.writeln("})");
document.writeln("$(\'.btnjs07\').click(function(){");
document.writeln("$(\'.dialog07\').fadeIn()");
document.writeln("})");
document.writeln("$(\'.btnjs08\').click(function(){");
document.writeln("$(\'.dialog08\').fadeIn()");
document.writeln("})");
document.writeln("$(\'.gbi\').click(function(){");
document.writeln("    $(\'.dialog\').fadeOut();");
document.writeln("  });");
document.writeln("</script>");